databases:
  - name: task_manager_base
    plan: free
    databaseName: task_manager_base
    user: postgres

services:
  - type: web
    plan: free
    name: task_manager
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'uv run gunicorn task-task_manager.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager_base
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4